"""Structural guarantees about the API surface."""

from __future__ import annotations

from starlette.routing import Route

from app.main import create_app

# Generated by FastAPI itself, not part of our API surface.
_FRAMEWORK_PATHS = {"/openapi.json", "/docs", "/docs/oauth2-redirect", "/redoc"}


def test_every_route_lives_under_api_v1() -> None:
    """CLAUDE.md §3 rule 3, made self-enforcing as the API grows.

    "All endpoints live under /api/v1/. No exceptions, not even health checks
    that obviously won't change."
    """
    app = create_app()

    offenders = [
        route.path
        for route in app.routes
        if isinstance(route, Route)
        and route.path not in _FRAMEWORK_PATHS
        and not route.path.startswith("/api/v1/")
    ]

    assert offenders == [], f"routes outside /api/v1: {offenders}"
