"""Structural guarantees about the API surface.

## A note on how routes are enumerated

FastAPI 0.141 does not flatten included routers into `app.routes`; it stores an opaque
`_IncludedRouter` wrapper instead. So `app.routes` contains only `/openapi.json` and
`/docs` -- which meant the original version of the first test below was passing
*vacuously*, seeing nothing but the framework paths it already excluded.

Two enumeration strategies are used here, both anchored on something stable:

* `app.openapi()["paths"]` -- the real, fully-prefixed URL of every documented route.
  A public API, and the same data a client sees.
* `_iter_api_routes()` -- descends into nested routers to reach the actual `APIRoute`
  objects, which is the only way to inspect a route's dependency tree. Note their `.path`
  is the *unprefixed* path (`/me`, not `/api/v1/me`), because the prefix is applied at
  include time.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any

from fastapi.dependencies.models import Dependant
from fastapi.routing import APIRoute

from app.api.deps import get_current_user
from app.main import create_app

# Generated by FastAPI itself, not part of our API surface.
_FRAMEWORK_PATHS = {"/openapi.json", "/docs", "/docs/oauth2-redirect", "/redoc"}

# Public by design. Unprefixed, because that is what APIRoute.path holds.
#
# Adding to this set is a deliberate, reviewed act -- test_the_health_check_is_the_only_
# unauthenticated_route below exists to make that true, and it asserts equality rather than
# containment so a forgotten role dependency cannot hide here.
#
# "/health":       an operator needs liveness without credentials, and it exposes only
#                  whether Postgres answers.
# "/auth-config":  Phase 12. A login screen cannot authenticate, so requiring a token to
#                  learn how to obtain a token cannot work. It returns SUPABASE_URL and
#                  SUPABASE_ANON_KEY -- both public by design; the anon key is *meant* to
#                  ship in a browser, unlike SUPABASE_SERVICE_KEY, which this route must
#                  never return and which tests/test_client_config.py asserts by name.
#
# Note that /client-config is deliberately NOT here: thresholds and the outlet name sit at
# the attendant floor. The split between the two routes is exactly this boundary.
_UNAUTHENTICATED_PATHS = {"/health", "/auth-config"}


def _iter_api_routes(node: Any) -> Iterator[APIRoute]:
    """Yield every APIRoute reachable from an app or router, descending into includes."""
    for route in getattr(node, "routes", []):
        if isinstance(route, APIRoute):
            yield route
            continue
        inner = getattr(route, "original_router", None)
        if inner is not None:
            yield from _iter_api_routes(inner)


def _requires_authentication(route: APIRoute) -> bool:
    """True if get_current_user appears anywhere in the route's dependency tree.

    Walks the whole tree rather than the top level, because require_role() reaches
    get_current_user indirectly, through the dependency it builds.
    """

    def walk(dependant: Dependant) -> bool:
        return any(
            sub.call is get_current_user or walk(sub)
            for sub in dependant.dependencies
        )

    return walk(route.dependant)


def test_every_route_lives_under_api_v1() -> None:
    """CLAUDE.md §3 rule 3, made self-enforcing as the API grows.

    "All endpoints live under /api/v1/. No exceptions, not even health checks
    that obviously won't change."
    """
    app = create_app()

    offenders = [
        path
        for path in app.openapi()["paths"]
        if path not in _FRAMEWORK_PATHS and not path.startswith("/api/v1/")
    ]

    assert offenders == [], f"routes outside /api/v1: {offenders}"


def test_route_enumeration_actually_finds_our_routes() -> None:
    """Guards the two tests below against passing vacuously.

    The original version of this module inspected app.routes, which on this FastAPI
    version contains no APIRoute at all -- so the assertions were true by default. A
    structural test that cannot fail is worse than no test, because it reads as coverage.
    """
    app = create_app()

    paths = {route.path for route in _iter_api_routes(app)}

    assert "/health" in paths
    assert "/me" in paths


def test_every_route_is_authenticated_unless_explicitly_exempt() -> None:
    """§8: "Enforced server-side on every endpoint."

    Self-enforcing so a future phase cannot ship an unguarded money endpoint: a new route
    that forgets its role dependency fails here rather than silently accepting anonymous
    writes.
    """
    app = create_app()

    unguarded = [
        route.path
        for route in _iter_api_routes(app)
        if route.path not in _UNAUTHENTICATED_PATHS
        and not _requires_authentication(route)
    ]

    assert unguarded == [], f"routes with no authentication: {unguarded}"


def test_only_the_explicitly_exempt_routes_are_unauthenticated() -> None:
    """Keeps the exempt list honest: adding to it should be a deliberate, reviewed act.

    Equality, not containment, and that asymmetry is the whole value of this test. A
    containment check (`public <= _UNAUTHENTICATED_PATHS`) would catch a new public route but
    would silently pass if `/health` quietly acquired a role dependency; equality fails in
    both directions, so the set stays an exact description of the public surface rather than
    an upper bound nobody revisits.

    Renamed in Phase 12, when `/auth-config` became the second member. The old name --
    `test_the_health_check_is_the_only_unauthenticated_route` -- had become a false statement
    that still passed, which is the shape of comment §14 warns about elsewhere: documentation
    that has drifted from the thing it documents is worse than none, because it is believed.
    """
    app = create_app()

    public = {
        route.path
        for route in _iter_api_routes(app)
        if not _requires_authentication(route)
    }

    assert public == _UNAUTHENTICATED_PATHS
